const product = [
    {
        id:1,
        name:"Slim Men Shirt",
        description:"  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium optio debiti",
        price:100,
        rating:5,
        brand:"Nike",
        category:"Shirt",
        image:"images/d1.jpg",
        reviews: 10
    },
    {
        id:2,
        name:"Slim Men Pant",
        description:"  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium optio debiti",
        price:80,
        rating:4.5,
        brand:"gucci",
        category:"pant",
        image:"images/d1.jpg",
        reviews: 18,
    },
    {
        id:3,
        name:"Men Suit shirt",
        description:"  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium optio debiti",
        price:90,
        rating:3.7,
        brand:"D&G",
        category:"Shirt",
        image:"images/d1.jpg",
        reviews: 8,
    },
    {
        id:4,
        name:"Fat Men Shirt",
        description:"  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium optio debiti",
        price:120,
        rating:5,
        brand:"Nike",
        category:"Shirt",
        image:"images/d1.jpg",
        reviews: 10,
    },
    {
        id:5,
        name:"Slim Men Trouser",
        description:"  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium optio debiti",
        price:100,
        rating:4.6,
        brand:"Platinum",
        category:"pants",
        image:"images/d1.jpg",
        reviews: 21,
    },
    {
        id:6,
        name:"Fat Men Trouser",
        description:"  Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium optio debiti",
        price:120,
        rating:5,
        brand:"Nike",
        category:"pants",
        image:"images/d1.jpg",
        reviews: 10,
    }
]

module.exports= product